CC = gcc


CFLAGS = -Wall -g

TARGET = minxProject

SRC = minxProject.c

OBJ = minxProject.o

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)


$(OBJ): $(SRC)
	$(CC) $(CFLAGS) -c $(SRC)

clean:
	rm -f $(OBJ) $(TARGET)
